#!/bin/sh

# run script to check if commit is valid
# you can run anything here, I happen to use a node script
node node_modules\\grunt-cli\\bin\\grunt jasmine
RETVAL=$?

if [ $RETVAL -ne 0 ]
then
  echo ""
  echo "Tests failed!"
  echo "ABORTING commmit!"
  exit 1
fi