#!/bin/sh

node node_modules\\grunt-cli\\bin\\grunt jasmine:all
RETVAL=$?

if [ $RETVAL -ne 0 ]
then
  echo "Tests failed!"
  echo "ABORTING commmit!"
  exit 1
fi

node node_modules\\grunt-cli\\bin\\grunt jasmine:istanbul
node gitHooks\\check-coverage.js
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
  echo ""
  echo "Coverage failed!"
  echo "ABORTING commmit!"
  exit 1
fi